version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: book-reading-api-assessment
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=book-reading-api-assessment
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: book-reading-api-assessment-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=book-reading-api-assessment
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql